name: Build_Docs

# 触发workflow的条件
on:
  push:
    # 只有 main 分支发生 push 事件时，才会触发 workflow
    branches:
      - master

# jobs表示执行的一项或多项任务
jobs:
  Build_Docs: # 任务的 job_id，具体名称自定义
    runs-on: ubuntu-latest # runs-on 字段指定运行所需要的虚拟机环境。注意：这个是必填字段
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - name: Build
        run: npm install && npm run docs:build
  # 部署到 GitHub Pages
      - name: Deploy
      # 使用别人写好的一个 action
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
        # 这里的 ACCESS_TOKEN 名字需要和下文中的相对应
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        # 打包后的文件部署到哪个分支上
          BRANCH: gh-pages
        # 打包后的文件在哪里
          FOLDER: docs